const W = import.meta.env.DEV ? '/wiki-images' : 'https://www.tibiawiki.com.br/images';

const ITEM_ICONS: Record<string, string> = {
  'Minotaur Leather': `${W}/9/9a/Minotaur_Leather.gif`,
  'Chicken Feather': `${W}/9/9a/Chicken_Feather.gif`,
  'Honeycomb': `${W}/2/2a/Honeycomb.gif`,
  'Legion Helmet': `${W}/6/60/Legion_Helmet.gif`,
  'Music Sheet': `${W}/a/ab/Music_Sheet.gif`,
  'Lizard Leather': `${W}/2/24/Lizard_Leather.gif`,
  'Red Dragon Leather': `${W}/a/aa/Red_Dragon_Leather.gif`,
  'Enchanted Chicken Wing': `${W}/8/84/Enchanted_Chicken_Wing.gif`,
  'Piece of Royal Steel': `${W}/4/40/Piece_of_Royal_Steel.gif`,
  'Piece of Draconian Steel': `${W}/a/aa/Piece_of_Draconian_Steel.gif`,
  'Piece of Hell Steel': `${W}/2/2a/Piece_of_Hell_Steel.gif`,
  'Sniper Gloves': `${W}/b/b9/Sniper_Gloves.gif`,
  'Iron Ore': `${W}/7/74/Iron_Ore.gif`,
  'Huge Chunk of Crude Iron': `${W}/8/80/Huge_Chunk_of_Crude_Iron.gif`,
  'Perfect Behemoth Fang': `${W}/c/c4/Perfect_Behemoth_Fang.gif`,
  'Flask of Warrior\'s Sweat': `${W}/5/5a/Flask_of_Warrior%27s_Sweat.gif`,
  'Wand of Vortex': `${W}/8/84/Wand_of_Vortex.gif`,
  'Wand of Dragonbreath': `${W}/3/34/Wand_of_Dragonbreath.gif`,
  'Wand of Decay': `${W}/b/ba/Wand_of_Decay.gif`,
  'Wand of Cosmic Energy': `${W}/8/84/Wand_of_Cosmic_Energy.gif`,
  'Wand of Inferno': `${W}/e/e3/Wand_of_Inferno.gif`,
  'Snakebite Rod': `${W}/9/9f/Snakebite_Rod.gif`,
  'Moonlight Rod': `${W}/7/74/Moonlight_Rod.gif`,
  'Necrotic Rod': `${W}/2/2c/Necrotic_Rod.gif`,
  'Terra Rod': `${W}/9/9f/Terra_Rod.gif`,
  'Hailstorm Rod': `${W}/3/34/Hailstorm_Rod.gif`,
  'Magic Sulphur': `${W}/2/2a/Magic_Sulphur.gif`,
  'Ankh': `${W}/9/9a/Ankh.gif`,
  'Soul Stone': `${W}/e/e3/Soul_Stone.gif`,
  'Ferumbras\' Hat': `${W}/4/40/Ferumbras%27_Hat.gif`,
  'Red Piece of Cloth': `${W}/7/74/Red_Piece_of_Cloth.gif`,
  'Green Piece of Cloth': `${W}/2/2c/Green_Piece_of_Cloth.gif`,
  'Spool of Yarn': `${W}/b/ba/Spool_of_Yarn.gif`,
  'Bat Wing': `${W}/a/aa/Bat_Wing.gif`,
  'Ape Fur': `${W}/8/84/Ape_Fur.gif`,
  'Holy Orchid': `${W}/9/9a/Holy_Orchid.gif`,
  'Lizard Scale': `${W}/e/e3/Lizard_Scale.gif`,
  'Red Dragon Scale': `${W}/7/74/Red_Dragon_Scale.gif`,
  'Vampire Dust': `${W}/3/34/Vampire_Dust.gif`,
  'Hardened Bones': `${W}/c/c4/Hardened_Bones.gif`,
  'Turtle Shell': `${W}/2/2c/Turtle_Shell.gif`,
  'Blue Piece of Cloth': `${W}/a/ab/Blue_Piece_of_Cloth.gif`,
  'Brown Piece of Cloth': `${W}/2/2a/Brown_Piece_of_Cloth.gif`,
  'Yellow Piece of Cloth': `${W}/7/74/Yellow_Piece_of_Cloth.gif`,
  'White Piece of Cloth': `${W}/e/e3/White_Piece_of_Cloth.gif`,
  'Behemoth Claw': `${W}/9/9a/Behemoth_Claw.gif`,
  'Nose Ring': `${W}/3/34/Nose_Ring.gif`,
  'Eye Patch': `${W}/b/ba/Eye_Patch.gif`,
  'Peg Leg': `${W}/a/ab/Peg_Leg.gif`,
  'Hook': `${W}/2/2c/Hook.gif`,
  'Banana Staff': `${W}/9/9a/Banana_Staff.gif`,
  'Tribal Mask': `${W}/e/e3/Tribal_Mask.gif`,
  'Dworc Voodoo Doll': `${W}/3/34/Dworc_Voodoo_Doll.gif`,
  'Mandrake': `${W}/a/ab/Mandrake.gif`,

  // Taming Items
  'Astral Shaper Rune': `${W}/6/6b/Astral_Shaper_Rune.gif`,
  'Bag of Apple Slices': `${W}/4/44/Bag_of_Apple_Slices.gif`,
  'Bamboo Leaves': `${W}/2/24/Bamboo_Leaves.gif`,
  'Beer Tap': `${W}/c/c0/Beer_Tap.gif`,
  'Bunch of Turnips': `${W}/0/0c/Bunch_of_Turnips.gif`,
  'Candle Stump': `${W}/2/20/Candle_Stump.gif`,
  'Carrot on a Stick': `${W}/b/b7/Carrot_on_a_Stick.gif`,
  'Colourful Water Lily': `${W}/1/1c/Colourful_Water_Lily.gif`,
  'Control Unit': `${W}/9/98/Control_Unit.gif`,
  'Crackling Egg': `${W}/c/c0/Crackling_Egg.gif`,
  'Decorative Blue Sheet': `${W}/f/f7/Decorative_Blue_Sheet.gif`,
  'Decorative Green Sheet': `${W}/8/8c/Decorative_Green_Sheet.gif`,
  'Decorative Red Sheet': `${W}/1/1c/Decorative_Red_Sheet.gif`,
  'Decorative Ribbon': `${W}/5/57/Decorative_Ribbon.gif`,
  'Demon in a Golden Box': `${W}/2/22/Demon_in_a_Golden_Box.gif`,
  'Demon In A Green Box': `${W}/1/1b/Demon_In_A_Green_Box.gif`,
  'Demon in a Red Box': `${W}/1/19/Demon_in_a_Red_Box.gif`,
  'Diapason': `${W}/4/43/Diapason.gif`,
  'Eldritch Crystal': `${W}/1/1e/Eldritch_Crystal.gif`,
  'Fiery Horseshoe': `${W}/8/8d/Fiery_Horseshoe.gif`,
  'Fist on a Stick': `${W}/5/50/Fist_on_a_Stick.gif`,
  'Four-Leaf Clover': `${W}/a/af/Four-Leaf_Clover.gif`,
  'Foxtail': `${W}/1/16/Foxtail.gif`,
  'Giant Shrimp': `${W}/b/b6/Giant_Shrimp.gif`,
  'Glow Wine': `${W}/c/ce/Glow_Wine.gif`,
  'Golden Can of Oil': `${W}/e/e1/Golden_Can_of_Oil.gif`,
  'Golden Fir Cone': `${W}/8/8d/Golden_Fir_Cone.gif`,
  'Golem Wrench': `${W}/a/ad/Golem_Wrench.gif`,
  'Harness': `${W}/2/25/Harness.gif`,
  'Hunting Horn': `${W}/e/e7/Hunting_Horn.gif`,
  'Iron Loadstone': `${W}/2/25/Iron_Loadstone.gif`,
  'Leather Whip': `${W}/4/44/Leather_Whip.gif`,
  'Leech': `${W}/0/09/Leech.gif`,
  'Library Ticket': `${W}/5/5c/Library_Ticket.gif`,
  'Marinated Sturgeon': `${W}/4/4c/Marinated_Sturgeon.gif`,
  'Maxilla Maximus': `${W}/2/25/Maxilla_Maximus.gif`,
  'Melting Horn': `${W}/4/42/Melting_Horn.gif`,
  'Menacing Egg': `${W}/3/31/Menacing_Egg.gif`,
  'Music Box': `${W}/b/ba/Music_Box.gif`,
  'Nail Case': `${W}/a/ac/Nail_Case.gif`,
  'Nightmare Horn': `${W}/6/6c/Nightmare_Horn.gif`,
  'Pegasus Feather': `${W}/e/e7/Pegasus_Feather.gif`,
  'Percht Skull': `${W}/4/40/Percht_Skull.gif`,
  'Purple Tendril Lantern': `${W}/f/f8/Purple_Tendril_Lantern.gif`,
  'Red Silk Flower': `${W}/9/91/Red_Silk_Flower.gif`,
  'Reins': `${W}/9/91/Reins.gif`,
  'Scorpion Sceptre': `${W}/e/eb/Scorpion_Sceptre.gif`,
  'Slingshot': `${W}/0/0b/Slingshot.gif`,
  'Slug Drug': `${W}/5/58/Slug_Drug.gif`,
  'Spectral Horse Tack': `${W}/6/6f/Spectral_Horse_Tack.gif`,
  'Spectral Horseshoe': `${W}/f/fe/Spectral_Horseshoe.gif`,
  'Spectral Saddle': `${W}/b/b2/Spectral_Saddle.gif`,
  'Spectral Scrap of Cloth': `${W}/d/da/Spectral_Scrap_of_Cloth.gif`,
  'Spiritual Horseshoe': `${W}/5/5c/Spiritual_Horseshoe.gif`,
  'Sugar Oat': `${W}/b/b4/Sugar_Oat.gif`,
  'Sweet Smelling Bait': `${W}/d/df/Sweet_Smelling_Bait.gif`,
  "The Lion's Heart": `${W}/c/c9/The_Lion%27s_Heart.gif`,
  'The Regalia of Suon': `${W}/1/1e/The_Regalia_of_Suon.gif`,
  'Tin Key': `${W}/f/fe/Tin_Key.gif`,
  'Toy Ball': `${W}/3/30/Toy_Ball.gif`,
  'Turquoise Tendril Lantern': `${W}/c/c2/Turquoise_Tendril_Lantern.gif`,
  'Vibrant Egg': `${W}/6/66/Vibrant_Egg.gif`,
  'Wind-Up Key': `${W}/7/7b/Wind-Up_Key.gif`,

  // Addon Items
  'Plague Bell': `${W}/6/66/Plague_Bell.gif`,
  'Plague Mask': `${W}/9/9d/Plague_Mask.gif`,
  'Broken Iks Cuirass': `${W}/c/c4/Broken_Iks_Cuirass.gif`,
  'Broken Iks Faulds': `${W}/b/b4/Broken_Iks_Faulds.gif`,
  'Broken Iks Headpiece': `${W}/3/31/Broken_Iks_Headpiece.gif`,
  'Broken Iks Sandals': `${W}/f/f4/Broken_Iks_Sandals.gif`,
  'Spirit Container': `${W}/1/1d/Spirit_Container_%28Fighting_Spirit%29.gif`,
  'Epaulettes': `${W}/0/00/Epaulette.gif`,
  "Simon The Beggar's Hat": `${W}/4/4a/Simon_The_Beggar%27s_Hat.gif`,
  'Document of the Officer': `${W}/9/94/Document_of_the_Officer.gif`,
  'Document of the Leader': `${W}/d/d3/Document_of_the_Leader.gif`,
  'Eye-Embroidered Veil': `${W}/2/23/Eye-Embroidered_Veil.gif`,
  'Tagralt-Inlaid Scabbard': `${W}/8/8f/Tagralt-Inlaid_Scabbard.gif`,
  'Gnomish Voucher Type CA1': `${W}/4/40/Gnomish_Voucher_Type_CA1.gif`,
  'Gnomish Voucher Type CA2': `${W}/b/b4/Gnomish_Voucher_Type_CA2.gif`,
  'Gnomish Voucher Type MA1': `${W}/6/60/Gnomish_Voucher_Type_MA1.gif`,
  'Gnomish Voucher Type MA2': `${W}/3/30/Gnomish_Voucher_Type_MA2.gif`,
  'Cursed Wood': `${W}/2/27/Cursed_Wood.gif`,
  'Darklight Geode': `${W}/9/9b/Darklight_Geode.gif`,
  "Jaul's Pearl": `${W}/e/eb/Jaul%27s_Pearl.gif`,
  "Obujos' Shell": `${W}/6/6d/Obujos%27_Shell.gif`,
  "Tanjis' Sight": `${W}/b/b9/Tanjis%27_Sight.gif`,
  'Small Golden Anchor': `${W}/a/a9/Small_Golden_Anchor.gif`,
  'Dream Warden Mask': `${W}/d/db/Dream_Warden_Mask.gif`,
  'Dream Warden Claw': `${W}/c/c6/Dream_Warden_Claw.gif`,
  'Pomegranates': `${W}/f/f1/Pomegranate.gif`,
  'Ice Shield': `${W}/3/37/Ice_Shield.gif`,
  "Mage's Cap": `${W}/2/22/Mage%27s_Cap.gif`,
  'Elemental Spikes': `${W}/f/fc/Elemental_Spikes.gif`,
  'Final Judgement': `${W}/2/2c/Final_Judgement.gif`,
  'Shadow Cowl': `${W}/a/ae/Shadow_Cowl.gif`,
  'Engraved Crossbow': `${W}/e/e1/Engraved_Crossbow.gif`,
  'Damaged Steel Helmet': `${W}/d/d4/Damaged_Steel_Helmet.gif`,
  'Crude Wood Planks': `${W}/3/37/Crude_Wood_Planks.gif`,
  'Tinged Pot': `${W}/d/d1/Tinged_Pot.gif`,
  'Wedding Rings': `${W}/a/ab/Wedding_Rings.gif`,
  'Frostheart Shards': `${W}/9/96/Frostheart_Shard.gif`,
  "Ron the Ripper's Sabre": `${W}/e/ee/Ron_the_Ripper%27s_Sabre.gif`,
  "Deadeye Devious' Eye Patch": `${W}/e/ef/Deadeye_Devious%27_Eye_Patch.gif`,
  "The Lethal Lissy's Shirt": `${W}/f/f5/The_Lethal_Lissy%27s_Shirt.gif`,
  "Brutus Bloodbeard's Hat": `${W}/e/ef/Brutus_Bloodbeard%27s_Hat.gif`,
  'Spooky Hood': `${W}/1/1c/Spooky_Hood.gif`,
  'Ghost Claw': `${W}/f/ff/Ghost_Claw.gif`,
  'Soap': `${W}/b/b8/Soap.gif`,
  'Scrubbing Brush': `${W}/3/36/Scrubbing_Brush.gif`,
  'Silver Token': `${W}/2/2f/Silver_Token.gif`,
  'Serpent Crest': `${W}/0/0c/Serpent_Crest.gif`,
  'Tribal Crest': `${W}/0/0a/Tribal_Crest.gif`,
  'Old Cape': `${W}/e/e2/Old_Cape.gif`,
  'Sedge Hat': `${W}/5/56/Sedge_Hat.gif`,
  'Vampiric Crest': `${W}/9/9c/Vampiric_Crest.gif`,
};

export function getItemIconUrl(itemName: string): string | null {
  return ITEM_ICONS[itemName] || null;
}
