const W = import.meta.env.DEV ? '/wiki-images' : 'https://www.tibiawiki.com.br/images';

const ITEM_ICONS: Record<string, string> = {
  'Minotaur Leather': `${W}/9/9a/Minotaur_Leather.gif`,
  'Chicken Feather': `${W}/9/9a/Chicken_Feather.gif`,
  'Honeycomb': `${W}/2/2a/Honeycomb.gif`,
  'Legion Helmet': `${W}/6/60/Legion_Helmet.gif`,
  'Music Sheet': `${W}/a/ab/Music_Sheet.gif`,
  'Lizard Leather': `${W}/2/24/Lizard_Leather.gif`,
  'Red Dragon Leather': `${W}/a/aa/Red_Dragon_Leather.gif`,
  'Enchanted Chicken Wing': `${W}/8/84/Enchanted_Chicken_Wing.gif`,
  'Piece of Royal Steel': `${W}/4/40/Piece_of_Royal_Steel.gif`,
  'Piece of Draconian Steel': `${W}/a/aa/Piece_of_Draconian_Steel.gif`,
  'Piece of Hell Steel': `${W}/2/2a/Piece_of_Hell_Steel.gif`,
  'Sniper Gloves': `${W}/b/b9/Sniper_Gloves.gif`,
  'Iron Ore': `${W}/7/74/Iron_Ore.gif`,
  'Huge Chunk of Crude Iron': `${W}/8/80/Huge_Chunk_of_Crude_Iron.gif`,
  'Perfect Behemoth Fang': `${W}/c/c4/Perfect_Behemoth_Fang.gif`,
  'Flask of Warrior\'s Sweat': `${W}/5/5a/Flask_of_Warrior%27s_Sweat.gif`,
  'Wand of Vortex': `${W}/8/84/Wand_of_Vortex.gif`,
  'Wand of Dragonbreath': `${W}/3/34/Wand_of_Dragonbreath.gif`,
  'Wand of Decay': `${W}/b/ba/Wand_of_Decay.gif`,
  'Wand of Cosmic Energy': `${W}/8/84/Wand_of_Cosmic_Energy.gif`,
  'Wand of Inferno': `${W}/e/e3/Wand_of_Inferno.gif`,
  'Snakebite Rod': `${W}/9/9f/Snakebite_Rod.gif`,
  'Moonlight Rod': `${W}/7/74/Moonlight_Rod.gif`,
  'Necrotic Rod': `${W}/2/2c/Necrotic_Rod.gif`,
  'Terra Rod': `${W}/9/9f/Terra_Rod.gif`,
  'Hailstorm Rod': `${W}/3/34/Hailstorm_Rod.gif`,
  'Magic Sulphur': `${W}/2/2a/Magic_Sulphur.gif`,
  'Ankh': `${W}/9/9a/Ankh.gif`,
  'Soul Stone': `${W}/e/e3/Soul_Stone.gif`,
  'Ferumbras\' Hat': `${W}/4/40/Ferumbras%27_Hat.gif`,
  'Red Piece of Cloth': `${W}/7/74/Red_Piece_of_Cloth.gif`,
  'Green Piece of Cloth': `${W}/2/2c/Green_Piece_of_Cloth.gif`,
  'Spool of Yarn': `${W}/b/ba/Spool_of_Yarn.gif`,
  'Bat Wing': `${W}/a/aa/Bat_Wing.gif`,
  'Ape Fur': `${W}/8/84/Ape_Fur.gif`,
  'Holy Orchid': `${W}/9/9a/Holy_Orchid.gif`,
  'Lizard Scale': `${W}/e/e3/Lizard_Scale.gif`,
  'Red Dragon Scale': `${W}/7/74/Red_Dragon_Scale.gif`,
  'Vampire Dust': `${W}/3/34/Vampire_Dust.gif`,
  'Hardened Bones': `${W}/c/c4/Hardened_Bones.gif`,
  'Turtle Shell': `${W}/2/2c/Turtle_Shell.gif`,
  'Blue Piece of Cloth': `${W}/a/ab/Blue_Piece_of_Cloth.gif`,
  'Brown Piece of Cloth': `${W}/2/2a/Brown_Piece_of_Cloth.gif`,
  'Yellow Piece of Cloth': `${W}/7/74/Yellow_Piece_of_Cloth.gif`,
  'White Piece of Cloth': `${W}/e/e3/White_Piece_of_Cloth.gif`,
  'Behemoth Claw': `${W}/9/9a/Behemoth_Claw.gif`,
  'Nose Ring': `${W}/3/34/Nose_Ring.gif`,
  'Eye Patch': `${W}/b/ba/Eye_Patch.gif`,
  'Peg Leg': `${W}/a/ab/Peg_Leg.gif`,
  'Hook': `${W}/2/2c/Hook.gif`,
  'Banana Staff': `${W}/9/9a/Banana_Staff.gif`,
  'Tribal Mask': `${W}/e/e3/Tribal_Mask.gif`,
  'Dworc Voodoo Doll': `${W}/3/34/Dworc_Voodoo_Doll.gif`,
  'Mandrake': `${W}/a/ab/Mandrake.gif`,
};

export function getItemIconUrl(itemName: string): string | null {
  return ITEM_ICONS[itemName] || null;
}
